// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.6
// source: space/space.proto

package space

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SpacerClient is the client API for Spacer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpacerClient interface {
	Do(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type spacerClient struct {
	cc grpc.ClientConnInterface
}

func NewSpacerClient(cc grpc.ClientConnInterface) SpacerClient {
	return &spacerClient{cc}
}

func (c *spacerClient) Do(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/space.Spacer/Do", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpacerServer is the server API for Spacer service.
// All implementations must embed UnimplementedSpacerServer
// for forward compatibility
type SpacerServer interface {
	Do(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedSpacerServer()
}

// UnimplementedSpacerServer must be embedded to have forward compatible implementations.
type UnimplementedSpacerServer struct {
}

func (UnimplementedSpacerServer) Do(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Do not implemented")
}
func (UnimplementedSpacerServer) mustEmbedUnimplementedSpacerServer() {}

// UnsafeSpacerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpacerServer will
// result in compilation errors.
type UnsafeSpacerServer interface {
	mustEmbedUnimplementedSpacerServer()
}

func RegisterSpacerServer(s grpc.ServiceRegistrar, srv SpacerServer) {
	s.RegisterService(&Spacer_ServiceDesc, srv)
}

func _Spacer_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpacerServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/space.Spacer/Do",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpacerServer).Do(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Spacer_ServiceDesc is the grpc.ServiceDesc for Spacer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Spacer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "space.Spacer",
	HandlerType: (*SpacerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _Spacer_Do_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "space/space.proto",
}
